name: KMPAutoPull
on:
  push:
    branches: [ "main" ]
workflow_dispatch:
jobs:
  autoupdate:
    name: autoupdate
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'