name: PullGeiAutomatico
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  PullGeiAutomatico:
    name: PullGeiAutomatico
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Recuperar cambios
        run:
          git reset --hard origin/main
      - name: copiar archivos sexo
        run:
          cp -Force $Env:GITHUB_WORKSPACE $Env:carpeta_mods -Recurse -PassThru