name: PullGeiAutomatico
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  PullGeiAutomatico:
    name: PullGeiAutomatico
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Recuperar cambios
        run:
          git reset --hard origin/main
      - name: copiar archivos sexo
        run:
          cp $Env:GITHUB_WORKSPACE $Env:carpeta_mods