name: PullGeiAutomatico
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  PullGeiAutomatico:
    name: PullGeiAutomatico
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Recuperar cambios
        run:
          git reset --hard origin/main
      - name: leer variable GitHub Workspace
        run:
          echo $Env:GITHUB_WORKSPACE
      - name: leer variable carpeta_mods
        run:
          echo $Env:carpeta_mods
      - name: probar si anda el echo
        run:
          echo HOLA
      - name: cambiar carpeta
        run:
          cd $Env:carpeta_mods
      - name: imprimir carpeta
        run:
          pwd